name: work_meter
description: WorkMeter - A modern time tracking and attendance management application built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  shared_preferences: ^2.2.3
  toast: ^0.3.0
  percent_indicator: "^4.2.3"
  intl: ^0.19.0
  rflutter_alert: ^2.0.7
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  # image: "2.1.4"

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: digit
      fonts:
        - asset: assets/fonts/DS-DIGI.TTF
    - family: roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: spectral
      fonts:
        - asset: assets/fonts/Spectral-Regular.ttf
          weight: 400
        - asset: assets/fonts/Spectral-Medium.ttf
          weight: 500
    - family: openSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: Courgette
      fonts:
        - asset: assets/fonts/Courgette-Regular.ttf

